name: .NET CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./BloodDonationSystem.sln

    - name: Build
      run: dotnet build ./BloodDonationSystem.sln --no-restore

    - name: Test
      run: dotnet test ./BloodDonationSystem.sln --no-build --verbosity normal
